routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/', function () {
    if (auth()->check()) {
        return redirect('/dashboard');
    } else {
        return redirect('/login');
    }
});

Route::get('/home', function () {
    return redirect('/dashboard');
});

/*
   |--------------------------------------------------------------------------
   | Routes Without authentication
   |--------------------------------------------------------------------------
 */
Route::get('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('/password/forgot', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::get('/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password_reset_save');
Route::post('/reset/password', 'Auth\ResetPasswordController@reset')->name('password.reset');


Auth::routes();

Route::group(['middleware' => 'auth'], function () {


    Route::group(['namespace' => 'Auth'], function () {

        Route::get('update-profile', 'ProfileController@editProfile')->name('edit.profile');
        Route::post('update-profile', 'ProfileController@updateProfile')->name('update.profile');

        Route::get('logout', 'LoginController@logout')->name('logout');
    });

    /*
      |--------------------------------------------------------------------------
      | Super Admin Routes
      |--------------------------------------------------------------------------
    */
    Route::group(['namespace' => 'Backend'], function () {

        //After Login redirect to dashboard
        Route::get('dashboard', 'DashboardController@index')->name('dashboard');

        Route::resource('users', 'UserController');
        Route::get('users/delete/{id}', ['as' => 'users.delete', 'uses' => 'UserController@destroy']);

        Route::resource('roles', 'RoleController');
        Route::get('roles/delete/{id}', ['as' => 'roles.delete', 'uses' => 'RoleController@destroy']);


    });
});

app/User.php
<?php

namespace App;

use App\Notifications\ResetPasswordLink;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laratrust\Traits\LaratrustUserTrait;

class User extends Authenticatable
{
    use Notifiable;
    use LaratrustUserTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPasswordLink($token));
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Repositories\Backend\Dashboard\DashboardContract;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;

class DashboardController extends Controller
{
    protected $repository;

    public function __construct(DashboardContract $repository)
    {
        $this->repository = $repository;
    }

    //return all the reservation record from database
    public function index()
    {
        try {
            $user_count = User::all()->count();
            return view('backend.dashboard', compact('user_count'));

        } catch (\Exception $e) {
            Log::error('Dashboard error:' . $e->getMessage());
            return redirect()->route('dashboard')->with('failure', 'Something went wrong');

        }
    }


}

app/Http/Controllers/Backend/RoleController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Requests\Backend\RoleStoreRequest;
use App\Http\Requests\Backend\UserStoreRequest;
use App\Http\Controllers\Controller;
use App\Repositories\Backend\Role\RoleContract;
use App\Repositories\Backend\User\UserContract;
use Illuminate\Support\Facades\Log;

class RoleController extends Controller
{
    protected $repository;

    public function __construct(RoleContract $repository)
    {
        $this->repository = $repository;
    }

    public function index()
    {
        try {
            $roles = $this->repository->getAll();
            return view('backend.roles.index', compact('roles'));

        } catch (\Exception $e) {
            Log::error('Role management error:' . $e->getMessage());
            return redirect()->route('roles.index')->with('failure', 'Something went wrong');
        }
    }

    public function create()
    {
        return view('backend.roles.form');
    }

    public function store(RoleStoreRequest $request)
    {
        try {
            $input = $request->only('name', 'display_name', 'description');
            $role = $this->repository->store($input);
            return redirect()->route('roles.index')->with('success', 'New Role added successfully');

        } catch (\Exception $e) {
            Log::error('Role management error:' . $e->getMessage() . 'on Line ' . $e->getLine() . '-->' . $e->getFile());
            return redirect()->route('roles.index')->with('failure', 'Something went wrong');
        }
    }

    public function edit($id)
    {
        try {
            $role = $this->repository->find($id);
            return view('backend.roles.form', compact('role'));

        } catch (\Exception $e) {
            Log::error('Role management error:' . $e->getMessage());
            return redirect()->route('roles.index')->with('failure', 'Something went wrong');
        }
    }

    public function update(RoleStoreRequest $request, $id)
    {

        try {
            $input = $request->only('name', 'display_name', 'description');
            $this->repository->update($id, $input);
            return redirect()->route('roles.index')->with('success', 'Role updated successfully');

        } catch (\Exception $e) {
            Log::error('Role management error:' . $e->getMessage() . 'on Line ' . $e->getLine() . '-->' . $e->getFile());
            return redirect()->route('roles.index')->with('Something went wrong');
        }
    }

    public function destroy($id)
    {
        try {
            $this->repository->delete($id);
            return redirect()->route('roles.index')->with('success', 'Role deleted successfully');

        } catch (\Exception $e) {
            Log::error('Role management error:' . $e->getMessage());
            return redirect()->route('roles.index')->with('failure', 'Something went wrong');
        }
    }
}

app/Http/Controllers/Backend/UserController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Requests\Backend\UserStoreRequest;
use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\UserUpdateRequest;
use App\Repositories\Backend\User\UserContract;
use App\Role;
use Illuminate\Support\Facades\Log;

class UserController extends Controller
{
    protected $repository;

    public function __construct(UserContract $repository)
    {
        $this->repository = $repository;
    }

    public function index()
    {
        try {
            $users = $this->repository->getAll();
            return view('backend.users.index', compact('users'));

        } catch (\Exception $e) {
            Log::error('User management error:' . $e->getMessage());
            return redirect()->route('users.index')->with('failure', 'Something went wrong');
        }
    }

    public function create()
    {
        $roles = Role::all();
        return view('backend.users.form', compact('roles'));
    }

    public function store(UserStoreRequest $request)
    {
        try {
            $input = $request->only('name', 'email', 'roles');
            $user = $this->repository->store($input);
            return redirect()->route('users.index')->with('success', 'New User added successfully');

        } catch (\Exception $e) {
            Log::error('User management error:' . $e->getMessage() . 'on Line ' . $e->getLine() . '-->' . $e->getFile());
            return redirect()->route('users.index')->with('failure', 'Something went wrong');
        }
    }

    public function edit($id)
    {
        try {
            $user = $this->repository->find($id);
            $roles = Role::all();
            return view('backend.users.form', compact('user','roles'));

        } catch (\Exception $e) {
            Log::error('User management error:' . $e->getMessage());
            return redirect()->route('users.index')->with('failure', 'Something went wrong');
        }
    }

    public function update(UserUpdateRequest $request, $id)
    {

        try {
            $input = $request->only('name', 'email', 'roles');
            $this->repository->update($id, $input);
            return redirect()->route('users.index')->with('success', 'User updated successfully');

        } catch (\Exception $e) {
            Log::error('User management error:' . $e->getMessage() . 'on Line ' . $e->getLine() . '-->' . $e->getFile());
            return redirect()->route('users.index')->with('Something went wrong');
        }
    }

    public function destroy($id)
    {
        try {
            $this->repository->delete($id);
            return redirect()->route('users.index')->with('success', 'User deleted successfully');

        } catch (\Exception $e) {
            Log::error('User management error:' . $e->getMessage());
            return redirect()->route('users.index')->with('failure', 'Something went wrong');
        }
    }
}

resources/views/backend/users/form.blade.php
@extends('backend.layouts.master')
@section('content')
    <div class="m-grid__item m-grid__item--fluid m-wrapper">
        <div class="m-subheader ">
            <div class="d-flex align-items-center">
                <div class="mr-auto">
                    <h3 class="m-subheader__title">
                        {{(isset($user))? 'Edit User' : 'Add User' }}
                    </h3>
                </div>
            </div>
        </div>

        <div class="m-content" style="width: 100%">
            <div class="m-portlet m-portlet--tab">
                <form id="form" class="m-form m-form--fit m-form--label-align-right"
                      action="{{ isset($user) ? route('users.update', $user->id) : route('users.store')}}"
                      method="POST" enctype="multipart/form-data">
                    @csrf
                    @if(isset($user))
                        @method('PUT')
                    @endif
                    <div class="m-portlet__body">

                        <div class="form-group row">
                            <div class="col-lg-6">
                                <div class="form-group m-form__group ">
                                    <label class="">
                                        Name*
                                    </label>
                                    <input type="text" class="form-control m-input" name="name"
                                           placeholder="Enter name"
                                           value="{!! isset($user) ? $user->name : old('name') !!}">
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group m-form__group ">
                                    <label class="">
                                        Email*
                                    </label>
                                    <input type="text" class="form-control m-input" name="email"
                                           placeholder="Enter email"
                                           value="{!! isset($user) ? $user->email : old('email') !!}">
                                </div>
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-lg-6">
                                <div class="form-group m-form__group ">
                                    <label class="">
                                        Select User Role*
                                    </label>
                                    <select class="form-control m-input" name="roles[]">
                                        <option value="" disabled selected>Select user role</option>
                                        @if(isset($roles) &&  count($roles) > 0)
                                            @foreach($roles as $role)
                                                <option
                                                    value="{{ $role->id }}" @if(isset($user) && $user->hasRole($role->name)) selected @endif>
                                                    {{ $role->display_name }}
                                                </option>
                                            @endforeach
                                        @endif
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="m-portlet__foot m-portlet__foot--fit">
                        <div class="m-form__actions">
                            <button type="submit" class="btn btn-primary">
                                Submit
                            </button>
                            <a href="{{ route('users.index') }}" class="btn btn-secondary">
                                Cancel
                            </a>
                        </div>
                    </div>
                </form>
                <!--end::Form-->
            </div>
        </div>
    </div>


@endsection
@section('scripts')

    <script>
        $(document).ready(function () {

            $.validator.setDefaults({
                debug: true,
                success: "valid"
            });
            $('#form').validate({
                rules: {
                    name: "required",
                    'roles[]': "required",
                    email: {
                        required: true,
                        email: true
                    },

                },
                messages: {
                    name: "Name field is required",
                    'roles[]': "Please select any role",
                    email: {
                        required: "Email Field is required",
                    }
                },
                submitHandler: function (form) {
                    form.submit();
                }
            });
        });
    </script>
@endsection

resources/views/backend/users/index.blade.php
@extends('backend.layouts.master')
@section('content')

    <div class="m-grid__item m-grid__item--fluid m-wrapper">
        <div class="m-subheader ">
            <div class="d-flex align-items-center">
                <div class="mr-auto">
                    <h3 class="m-subheader__title ">
                        Users
                    </h3>
                </div>
            </div>
        </div>


        <div class="m-content">
            <div class="m-portlet">

                <div class="m-portlet__body">
                    <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
                        <div class="row align-items-center">
                            <div class="col-xl-8 order-2 order-xl-1">
                                <div class="form-group m-form__group row align-items-center">
                                    <div class="col-md-4">
                                        <div class="m-input-icon m-input-icon--left">
                                            <input type="text" class="form-control m-input m-input--solid"
                                                   placeholder="Search" id="generalSearch">
                                            <span class="m-input-icon__icon m-input-icon__icon--left">
                                                <span>
                                                    <i class="la la-search"></i>
                                                </span>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-4 order-1 order-xl-2 m--align-right">
                                <a href="{{ route('users.create') }}"
                                   class="btn btn-accent m-btn m-btn--custom m-btn--icon m-btn--air m-btn--pill">
												<span>
													<i class="la flaticon-add-circular-button"></i>
													<span>
														Create User
													</span>
												</span>
                                </a>
                                <div class="m-separator m-separator--dashed d-xl-none"></div>
                            </div>
                        </div>
                    </div>
                    <div class="m_datatable" id="child_data_local"></div>
                </div>
            </div>
        </div>
    </div>

    <form id="deleteForm" method="post" action="" style="display: none;">
        @csrf
        @method('delete')
    </form>
    @include('backend.snippets.delete')
@endsection



@section('scripts')
    <script>

        $(document).on('click', '.delete-button-action', function (e) {
            $('#myModal').modal();
            $('#delete_btn').attr('href', '{{route('users.index')}}/delete/' + $(this).data('id'));
        });

        $(document).on('click', '.edit-button', function (e) {
            var editUrl = '{{route('users.index')}}/' + $(this).data('id') + '/edit';
            location.href = editUrl;
        });

        var users = {!! $users !!};
        console.log('users', users);


        var DatatableDataLocalDemo = {
            init: function () {
                var e, a, i;
                e = users, a = $(".m_datatable").mDatatable({
                    data: {
                        type: "local",
                        source: e,
                        pageSize: 10
                    },
                    layout: {theme: "default", class: "", scroll: !1, footer: !1},
                    sortable: !0,
                    pagination: !0,
                    search: {input: $("#generalSearch")},
                    columns: [{
                        field: "id",
                        title: "#",
                        width: 50,
                        sortable: 1,
                        textAlign: "center",
                        template: function (e, a, i) {
                            return  a + 1;
                        }
                    },  {
                        field: "name",
                        title: "Name",
                        width: 100,
                        sortable: 1,
                        // textAlign: "center",
                    }, {
                        field: "email",
                        title: "Email",
                        width: 250,
                        sortable: 1,
                        overflow: "visible",
                        // textAlign: "center",
                    }, {
                        field: "role",
                        title: "Role",
                        width: 250,
                        sortable: 1,
                        overflow: "visible",
                        template: function (e, a, i) {
                            if(e.user_roles.length > 0){
                                var data = '';
                                $.each(e.user_roles , function (key, value) {
                            data += '<button class="btn btn-primary" style="cursor: default"> ' + value.display_name + ' </button>';
                                });
                                return data;
                            } else {
                                return '';
                            }
                        }
                    },  {
                        field: "Actions",
                        width: 120,
                        title: "Action",
                        sortable: !1,
                        overflow: "visible",
                        template: function (e, a, i) {
                            var edit = '\t\t\t\t\t\t<a href="javascript:void(0);" data-id="' + e.id + '" ' +
                                'class="edit-button m-portlet__nav-link ' +
                                'btn m-btn ' +
                                'm-btn--hover-accent m-btn--icon m-btn--icon-only m-btn--pill" title="Edit">        ' +
                                '                    <i class="la la-edit"></i>                        </a>\t\t\t\t\t';
                            var deleteB = '\t\t\t\t\t\t<a href="javascript:void(0);" class="delete-button-action ' +
                                'm-portlet__nav-link ' +
                                'btn m-btn ' +
                                'm-btn--hover-danger m-btn--icon m-btn--icon-only ' +
                                'm-btn--pill" title="Delete " data-id="' + e.id + '">                            <i ' +
                                'class="fa fa-trash-o"' +
                                ' ' +
                                '></i>                        </a>\t\t\t\t\t';


                            return edit + '\t\t' + deleteB;
                        }
                    }]
                }), i = a.getDataSourceQuery(), $("#m_form_status").on("change", function () {
                    a.search($(this).val(), "Status")
                }).val(void 0 !== i.Status ? i.Status : ""), $("#m_form_type").on("change", function () {
                    a.search($(this).val(), "Type")
                }).val(void 0 !== i.Type ? i.Type : ""), $("#m_form_status, #m_form_type").selectpicker()
            }
        };
        jQuery(document).ready(function () {
            DatatableDataLocalDemo.init();

        });
    </script>
@endsection